<img src="../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a dataset at a high level with `pandas`.

### Notebook Guide
An exercise in practising:

- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Writing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

### Business question

What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

#### 1. Import `pandas` and read in the LEGO dataset

In [2]:
import pandas as pd
lego = pd.read_csv('./data/lego.csv')
lego.head()

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

#### 2. So we can focus on just the columns that help answer the question, select only the following columns into a new `DataFrame` variable:

- name
- theme
- number of pieces
- retail price (USD_MSRP)

In [3]:
lego2 = lego[['Name', 'Theme', 'Pieces', 'USD_MSRP']]
lego2.head()

             Name      Theme  Pieces  USD_MSRP
0   PreSchool Set  PreSchool    16.0       NaN
1   PreSchool Set  PreSchool    20.0       NaN
2  Pre-School Set      Duplo    21.0       NaN
3   PreSchool Set  PreSchool    32.0       NaN
4       Basic Set  Samsonite   330.0       NaN

#### 3. How many sets have a price greater than $100?

In [7]:
lego2[
    lego2['USD_MSRP'] > 100
].shape[0]

380

#### 4. What are the top 10 sets with the highest number of pieces?

In [22]:
# lego2['Name'][lego2['Pieces'].sort_values(ascending = False).head(10)].to_frame()

lego2.sort_values(by='Pieces', ascending=False).head(10)[['Name', 'Pieces']]

                                   Name   Pieces
13559                         World Map  11695.0
13946                      Eiffel Tower  10001.0
13449                           Titanic   9090.0
12942                         Colosseum   9036.0
11928                 Millennium Falcon   7541.0
14380                   The Razor Crest   6187.0
14440  The Lord of the Rings: Rivendell   6167.0
14807              NINJAGO City Markets   6163.0
12369                   Hogwarts Castle   6020.0
11437                         Taj Mahal   5923.0

#### 5. Create a new column to measure "price per piece", which should be the price (USD_MSRP) divided by the number of pieces

In [28]:
lego2['price_per_piece'] = lego2['USD_MSRP']/lego2['Pieces']
lego2[10000:15000]

                          Name   Theme  Pieces  USD_MSRP  price_per_piece
10000              Town Master  Fusion   256.0     34.99         0.136680
10001            Battle Towers  Fusion   212.0     34.99         0.165047
10002          Create and Race  Fusion   223.0     34.99         0.156906
10003          Resort Designer  Fusion   262.0     34.99         0.133550
10004        Farm {Random Bag}   Duplo     5.0       NaN              NaN
...                        ...     ...     ...       ...              ...
14931        Creeper Key Chain    Gear     NaN      5.99              NaN
14932          Steve Key Chain    Gear     NaN      5.99              NaN
14933         Piglin Key Chain    Gear     NaN      5.99              NaN
14934   Fennec Shand Key Chain    Gear     NaN      5.99              NaN
14935  Scout Trooper Key Chain    Gear     NaN      5.99              NaN

[4936 rows x 5 columns]

#### 6. Use this column to find the top 10 most expensive sets by "price per piece"

In [29]:
lego2.sort_values(by = 'price_per_piece', ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP,price_per_piece
14251,LEGO Minifigures - Series 22 {Box of 6 random ...,Collectable Minifigures,0.0,29.94,inf
13806,LEGO Minifigures - Marvel Studios Series {Box ...,Collectable Minifigures,0.0,29.94,inf
13892,Character Pack Series 3 - Complete,Super Mario,0.0,4.99,inf
9653,EV3 Intelligent Brick,Mindstorms,1.0,224.95,224.950
7695,Intelligent NXT Brick (Black),Mindstorms,1.0,169.99,169.990
6342,NXT Intelligent Brick,Mindstorms,1.0,169.99,169.990
13755,Small Hub,Education,2.0,214.95,107.475
9654,DC Rechargeable Battery,Education,1.0,99.95,99.950
12927,Boost Hub,Powered Up,1.0,79.99,79.990
8197,NXT DC Rechargeable Battery,Education,1.0,79.99,79.990

#### 7. Narrow the search to show the top 10 most expensive sets by "price per piece" for the "Icons" theme *only*

In [30]:
lego2[
    lego2['Theme'] == 'Icons'
].sort_values(by = 'price_per_piece', ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP,price_per_piece
13941,Optimus Prime,Icons,1508.0,179.99,0.119357
13943,Chevrolet Camaro Z/28 1969,Icons,1456.0,169.99,0.116751
13450,Porsche 911,Icons,1458.0,169.99,0.116591
13440,Adidas Originals Superstar,Icons,731.0,79.99,0.109425
13939,Back to the Future Time Machine,Icons,1872.0,199.99,0.106832
13942,Loop Coaster,Icons,3756.0,399.99,0.106494
14441,Land Rover Classic Defender 90,Icons,2336.0,239.99,0.102735
13446,Queer Eye – The Fab 5 Loft,Icons,974.0,99.99,0.102659
12940,Ghostbusters ECTO-1,Icons,2352.0,239.99,0.102037
13617,Everyone is Awesome,Icons,346.0,34.99,0.101127

#### 8. What are the top 10 cheapest sets by "price per piece" in the "Icons" theme?

In [31]:
lego2[
    lego2['Theme'] == 'Icons'
].sort_values(by = 'price_per_piece').head(10)

,Name,Theme,Pieces,USD_MSRP,price_per_piece
13439,Bonsai Tree,Icons,878.0,49.99,0.056936
14576,Daffodils,Icons,216.0,12.99,0.060139
12942,Colosseum,Icons,9036.0,549.99,0.060867
14438,Dried Flower Centrepiece,Icons,812.0,49.99,0.061564
13946,Eiffel Tower,Icons,10001.0,629.99,0.062993
13443,Camp Nou - FC Barcelona,Icons,5509.0,349.99,0.063531
14437,Wildflower Bouquet,Icons,939.0,59.99,0.063887
13948,Succulents,Icons,771.0,49.99,0.064838
13947,Holiday Main Street,Icons,1514.0,99.99,0.066044
13938,Real Madrid - Santiago Bernabéu Stadium,Icons,5876.0,399.99,0.068072

#### 9. Export the `DataFrame` you created in question 2. to a new CSV file.

In [34]:
lego2.to_csv('./data/newLego.csv', index = False)

### Reflection

What is your answer to the business question? Here it is as a reminder:

> What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

Reflect on your experience. How was working with `pandas` compared to other tools you already know?